title: State Courts Practice Directions 2021
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-state-courts-practice-directions-2021
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
offline: false
google_analytics: UA-113717369-8

styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo-full.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/'
    title: 'State Courts Practice Directions 2021'
    subtitle: ''
    order:
      - 'PART-01-Introduction.md'
      - 'PART-02-Originating-Processes-And-Documents.md'
      - 'PART-03-Simplified-Process-For-Civil-Proceedings-In-The-Magistrates-Court.md'
      - 'PART-03A-Documents-Only-Proceedings.md'
      - 'PART-04-Interlocutory-And-Other-Applications.md'
      - 'PART-05-Hearings-Via-Skype.md'
      - 'PART-06-Alternative-Dispute-Resolution.md'
      - 'PART-07-Discovery-And-Inspection-Of-Electronically-Stored-Documents.md'
      - 'PART-08-Evidence-Witnesses-Affidavits-And-Exhibits.md'
      - 'PART-09-Fixing-Of-Matters-For-Hearing.md'
      - 'PART-10-Documents-And-Authorities-For-Use-In-Court.md'
      - 'PART-11-Judgements-And-Orders.md'
      - 'PART-12-Appeals.md'
      - 'PART-13-Electronic-Filing-Service.md'
      - 'PART-14-Execution-Matters.md'
      - 'PART-15-Bills-Of-Costs-For-Taxation.md'
      - 'PART-16-General-Matters.md'
      - 'PART-17-Criminal-Matters.md'
      - 'PART-18-Electronic-Filing-And-Service-For-Criminal-Proceedings.md'
      - 'PART-19-Community-Disputes-Resolution.md'
      - 'PART-20-Employment-Claims.md'
      - 'PART-21-Defamation-Actions.md'
      - 'PART-22-Business-To-Business-Debt-Claims.md'
      - 'Part-23-Reference-to-Actuarial-Tables.md'
      - 'Part-24-Simplified-proceedings-under-the-protection-from-harrasment-act.md'
      - 'Part-25-Electronic-Filing-and-case-management-for-matters.md'
      - 'Appendices.md'
